float ballSpeed
float ballRadius
float goalSize
float friction
float buttonSpeed
int capture
int startStop
---
float ballSpeed
float ballRadius
float goalSize
float friction
float buttonSpeed
int capture
int startStop